"use client";

import { useState } from "react";
import { CheckCircle2, Loader2, LockKeyhole, Mail, UserRound } from "lucide-react";
import { useAuth } from "@/context/AuthContext";
import { Button } from "@/components/ui/Button";
import { Card, CardContent } from "@/components/ui/Card";

export default function CompleteProfilePage() {
  const { profile, completeEmailSetup } = useAuth();
  const [name, setName] = useState(profile?.name || ""); const [email, setEmail] = useState(profile?.email || ""); const [password, setPassword] = useState(""); const [confirm, setConfirm] = useState(""); const [loading, setLoading] = useState(false); const [error, setError] = useState("");
  async function submit(event: React.FormEvent) { event.preventDefault(); if (name.trim().length < 2) return setError("Enter your full name."); if (password.length < 8) return setError("Password must be at least 8 characters."); if (password !== confirm) return setError("Passwords do not match."); setLoading(true); setError(""); try { await completeEmailSetup(name, email, password); const requested = new URLSearchParams(window.location.search).get("returnTo"); window.location.replace(requested?.startsWith("/") && !requested.startsWith("//") ? requested : "/"); } catch (err: any) { setError(err?.code === 409 ? "This email already has an account. Return to sign in and use its password." : err?.message || "Profile could not be completed."); } finally { setLoading(false); } }
  return <Card className="border-slate-200 shadow-xl shadow-slate-200/60"><CardContent className="p-6 sm:p-7"><div className="grid size-11 place-items-center rounded-lg bg-emerald-50 text-emerald-700"><CheckCircle2 size={21}/></div><h1 className="mt-5 text-2xl font-black text-slate-950">Finish account setup</h1><p className="mt-2 text-sm leading-6 text-slate-500">Your verified phone approved this browser. Add the missing account details to enable future email sign-in.</p><form onSubmit={submit} className="mt-6 space-y-4"><Field icon={UserRound} label="Full name" type="text" value={name} onChange={setName} autoComplete="name"/><Field icon={Mail} label="Email address" type="email" value={email} onChange={setEmail} autoComplete="email"/><Field icon={LockKeyhole} label="Create password" type="password" value={password} onChange={setPassword} autoComplete="new-password"/><Field icon={LockKeyhole} label="Confirm password" type="password" value={confirm} onChange={setConfirm} autoComplete="new-password"/>{error ? <p className="rounded-md bg-orange-50 px-3 py-2 text-xs font-semibold text-orange-800">{error}</p> : null}<Button className="w-full" disabled={loading}>{loading ? <Loader2 className="h-4 w-4 animate-spin"/> : null}Complete setup</Button></form></CardContent></Card>;
}

function Field({ icon: Icon, label, type, value, onChange, autoComplete }: { icon: typeof UserRound; label: string; type: string; value: string; onChange: (value: string) => void; autoComplete: string }) { return <label className="block"><span className="text-xs font-bold text-slate-700">{label}</span><div className="relative mt-2"><Icon className="absolute left-3 top-3.5 h-4 w-4 text-slate-400"/><input required type={type} value={value} onChange={(event) => onChange(event.target.value)} autoComplete={autoComplete} className="h-11 w-full rounded-md border border-slate-300 pl-10 pr-3 text-sm"/></div></label>; }
